### ISSUE TITLE
Node support?

### ISSUE THREAD

**Issue by jesus2099** [kellnerd/cueshit#1]
🙇 Very sorry, it's a very lame/lazy question.
You probably know I suck at all those modern JavaScript libraries.

I managed to [easy install Node.js](https://github.com/jesus2099/konami-command/blob/41eaa92e1ef7adc1940f24ded66d4220277e100f/CONTRIBUTING.md?plain=1#L62-L65) (it did take me super long time to find out) and was wondering if I really need to install another thing like that (Deno) or if in fact this can be ran (how?) with Node?

I went on Deno website but didn't find out (yet) how to download and install.
I'm super lousy.

PS. Cueshit is a very nice name! 👍

**Comment by jesus2099** [comment]
Ach now I found. It was the first big green button on the https://deno.com website! 🤦‍♂️

**Comment by kellnerd** [comment]
No problem, thank you for the interest.
I've also spend a lot of time reading about Deno and wondering whether I really need it in addition to Node.js before I finally decided to give it a try.
Once I had installed it, I was surprised how easy everything was compared to Node.js, no need to install a dozen packages and set up lots of configuration files before you can start to write code (not even for TypeScript).
Only Deno's permission system and the URL import specifiers took me a bit to get used to.
